# Generated by Django 4.2.1 on 2023-05-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.CharField(default='task', max_length=255),
        ),
    ]
