# Generated by Django 4.2.1 on 2023-05-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0005_remove_todo_tags_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('working', 'working'), ('done', 'done'), ('over_due', 'over_due')], default='open', max_length=20),
        ),
    ]
